accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField()


class FriendShip(models.Model):
    following = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="friendships_by_following"
    )
    follower = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="friendships_by_follower"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["following", "follower"], name="follow_unique"),
        ]

tweets/models.py
from django.conf import settings
from django.db import models


class Tweet(models.Model):
    content = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.content


class Like(models.Model):
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE, related_name="likes")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="likes")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["tweet", "user"], name="unique_like"),
        ]

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from accounts.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email"]

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, View

from tweets.models import Like, Tweet

from .forms import SignupForm
from .models import FriendShip, User


class SignupView(CreateView):
    form_class = SignupForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password1"]
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)
        return response


class UserProfileView(LoginRequiredMixin, DetailView):
    model = User
    context_object_name = "user"
    template_name = "accounts/profile.html"
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        context["tweet_user"] = user
        context["tweet_list"] = (
            Tweet.objects.select_related("user").prefetch_related("likes").filter(user=user).order_by("-created_at")
        )
        context["is_following"] = FriendShip.objects.filter(following=user, follower=self.request.user).exists()
        context["following_num"] = FriendShip.objects.filter(follower=user).count()
        context["followers_num"] = FriendShip.objects.filter(following=user).count()
        liked_list = Like.objects.filter(user=self.request.user).values_list("tweet_id", flat=True)
        context["liked_list"] = liked_list
        return context


class FollowView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        following = get_object_or_404(User, username=self.kwargs["username"])
        follower = request.user

        if following == follower:
            return HttpResponseBadRequest("自分自身はフォローできません。")

        if FriendShip.objects.filter(following=following, follower=follower).exists():
            messages.warning(request, "フォロー済です。")
            return redirect("tweets:home")

        FriendShip.objects.create(following=following, follower=follower)
        messages.success(request, "フォローしました")
        return redirect("tweets:home")


class UnFollowView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        following = get_object_or_404(User, username=self.kwargs["username"])
        follower = request.user

        if following == follower:
            return HttpResponseBadRequest("自分自身を対象には出来ません。")

        FriendShip.objects.filter(following=following, follower=follower).delete()
        messages.success(request, "フォローを外しました")
        return redirect("tweets:home")


class FollowerListView(LoginRequiredMixin, ListView):
    model = User
    template_name = "accounts/follower_list.html"
    context_object_name = "follower_friendships"

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs["username"])
        return FriendShip.objects.select_related("follower").filter(following=user)


class FollowingListView(LoginRequiredMixin, ListView):
    model = User
    template_name = "accounts/following_list.html"
    context_object_name = "following_friendships"

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs["username"])
        return FriendShip.objects.select_related("following").filter(follower=user)

templates/accounts/follower_list.html
{% extends "base.html" %}

{% block title %}Followers{% endblock %}

{% block content %}
<h1>FollowerList</h1>
<ul>
    {% for follower_friendship in follower_friendships %}
    <li>
        <a href="{% url 'accounts:user_profile' follower_friendship.follower.username %}">
            {{follower_friendship.follower.username}}</a>
    </li>
    {% empty %}
    <p>フォローされているユーザーはいません</p>
    {% endfor %}
</ul>
{% endblock %}

templates/accounts/following_list.html
{% extends 'base.html' %}

{% block title %}FollowingList{% endblock %}

{% block content %}
<h1>FollowingList</h1>
<ul>
    {% for following_friendship in following_friendships %}
    <li>
        <a href="{% url 'accounts:user_profile' following_friendship.following.username %}">
            {{ following_friendship.following.username }}</a>
    </li>
    {% empty %}
    <p>フォローしているユーザーはいません</p>
    {% endfor %}
</ul>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}

<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">ログイン</button>
</form>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
<h1>profile</h1>
<div>
    <a href="{% url 'accounts:following_list' user.username %}">フォロー数:{{following_num}}</a>
    <a href="{% url 'accounts:follower_list' user.username %}">フォロワー数:{{followers_num}}</a>
    <div>
        <a href="{% url 'accounts:following_list' user.username %}">フォロー一覧</a>
        <a href="{% url 'accounts:follower_list' user.username %}">フォロワー一覧</a>
    </div>
</div>
<div>
    {% if request.user != user %}
    {% if is_following is True %}
    <form action="{%  url 'accounts:unfollow' user.username %}" method="POST"><button type="submit"
            id="unfollow">フォローを外す</button>
        {% csrf_token %}
    </form>
    {% else %}
    <form action="{%  url 'accounts:follow' user.username %}" method="POST"><button type="submit"
            id="follow">フォローする</button>
        {% csrf_token %}
    </form>
    <br>
    {% endif %}
    {% endif %}
</div>
<div class="container mt-3">
    {% for tweet in tweet_list %}
    <div>
        <a href="{% url 'accounts:user_profile' username=tweet.user %}"></a>{{ tweet.user }} {{ tweet.created_at }}
        <a href="{% url 'tweets:detail' tweet.pk %}">詳細</a>
    </div>
    <div>
        {{ tweet.content }}
    </div>
    {% include "tweets/like.html" %}
    {% endfor %}
</div>
{% include "tweets/like_js.html" %}
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %} <!--base.htmlを継承 -->

{% block title %}Sign Up{% endblock %} <!--titleを入れる -->

{% block content %}
<form method="post">
    {{ form.as_p }} <!--formにはSignupFormのインスタンスが入っている。as_pとすることで、各input要素がpタグで囲まれた状態で表示される。-->
    {% csrf_token %} <!--csrf_token必須。formタグ内であればどこに書いてもOK -->
    <button type="submit">ユーザー登録</button>
</form>
{% endblock %}