accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

tweets/models.py
from django.conf import settings
from django.db import models


class Tweet(models.Model):
    content = models.TextField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.content


class Like(models.Model):
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE, related_name="likes")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="likes")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["tweet", "user"], name="unique_like"),
        ]

tweets/forms.py
from django import forms

from .models import Tweet


class TweetCreateForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = [
            "content",
        ]

tweets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, View

from .forms import TweetCreateForm
from .models import Like, Tweet


class HomeView(LoginRequiredMixin, ListView):
    template_name = "tweets/home.html"
    model = Tweet

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tweet_list"] = Tweet.objects.select_related("user").prefetch_related("likes")
        liked_list = (
            Like.objects.filter(user=self.request.user).select_related("tweet").values_list("tweet_id", flat=True)
        )
        context["liked_list"] = liked_list
        return context


class TweetCreateView(LoginRequiredMixin, CreateView):
    template_name = "tweets/create.html"
    form_class = TweetCreateForm
    success_url = reverse_lazy("tweets:home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TweetDetailView(LoginRequiredMixin, DetailView):
    template_name = "tweets/detail.html"
    model = Tweet
    queryset = model.objects.select_related("user").prefetch_related("likes")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        liked_list = (
            Like.objects.select_related("tweet").filter(user=self.request.user).values_list("tweet_id", flat=True)
        )
        context["liked_list"] = liked_list
        return context


class TweetDeleteView(UserPassesTestMixin, DeleteView):
    template_name = "tweets/delete.html"
    model = Tweet
    success_url = reverse_lazy("tweets:home")

    def test_func(self):
        return self.request.user == self.get_object().user


class LikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        tweet_id = self.kwargs["pk"]
        tweet = get_object_or_404(Tweet, id=tweet_id)
        Like.objects.get_or_create(tweet=tweet, user=self.request.user)
        unlike_url = reverse("tweets:unlike", kwargs={"pk": tweet_id})
        tweet = Tweet.objects.prefetch_related("likes").get(id=tweet_id)
        like_count = tweet.likes.count()
        is_liked = True
        context = {
            "like_count": like_count,
            "tweet_id": tweet_id,
            "is_liked": is_liked,
            "unlike_url": unlike_url,
        }
        return JsonResponse(context)


class UnlikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        tweet_id = self.kwargs["pk"]
        tweet = get_object_or_404(Tweet, pk=tweet_id)
        like = Like.objects.filter(user=self.request.user, tweet=tweet)
        like.delete()
        is_liked = False
        like_url = reverse("tweets:like", kwargs={"pk": tweet_id})
        tweet = Tweet.objects.prefetch_related("likes").get(id=tweet_id)
        like_count = tweet.likes.count()
        context = {
            "like_count": like_count,
            "tweet_id": tweet_id,
            "is_liked": is_liked,
            "like_url": like_url,
        }
        return JsonResponse(context)

templates/tweets/create.html
{% extends "base.html" %}

{% block title %}Tweet Create{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="投稿">
</form>
{% endblock %}

templates/tweets/delete.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>この操作は取り消せません。削除してもよろしいですか？</p>
    <button type="submit" class="blueback">削除</button>
</form>
{% endblock %}

templates/tweets/detail.html
{% extends "base.html" %}

{% block title %}Detail{% endblock %}

{% block content %}
<h1>詳細</h1>
<div class="container">
    <div class="alert alert-success" role="alert">
        <p>投稿者:{{tweet.user}}</p>
        <p>コメント:{{tweet.content}}</p>
        {% include 'tweets/like.html' %}
        {% include "tweets/like_js.html" %}

        {% if tweet.user == request.user %}
        <a href="{% url 'tweets:delete' tweet.pk %}" class="btn btn-danger ms-3" tabindex="-1" role="button"
            aria-disabled="true">削除</a>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/tweets/home.html
{% extends "base.html" %} <!-- base.htmlを継承 -->

{% block title %}Home{% endblock %} <!-- titleを入れる -->

{% block content %}
<h1>Home</h1>
<div class="container mt-3">
    <a href="{% url 'tweets:create' %}"><button type="button" class="btn btn-outline-primary">tweet</button></a>
    {% for tweet in tweet_list %}
    <div class="p-4 m-4 bg-light border border-primary rounded">
        <p>作成者：<a href="{% url 'accounts:user_profile' tweet.user %}">{{ tweet.user }}</a></p>
        <p>作成日：{{ tweet.created_at }}</p>
        <p>内容：{{ tweet.content }}</p>
        <a href="{% url 'tweets:detail' tweet.pk %}" class='btn btn-primary'>詳細へ</a>
        {% include 'tweets/like.html' %}
    </div>
    {% endfor %}
</div>
{% include "tweets/like_js.html" %}
{% endblock %}

templates/tweets/like.html
{% if tweet.id in liked_list %}
<button id="tweet_{{tweet.id}}" onclick="changeLike(id)" data-url="{% url 'tweets:unlike' tweet.id %}">いいね解除</button>
{% else %}
<button id="tweet_{{tweet.id}}" onclick="changeLike(id)" data-url="{% url 'tweets:like' tweet.id %}">いいね</button>
{% endif %}
<span class="count_{{tweet.id}}">{{tweet.likes.count}}</span><a>いいね</a>

templates/tweets/like_js.html
<script>
    const getCookie = (name) => {
        if (document.cookie && document.cookie !== '') {
            for (const cookie of document.cookie.split(';')) {
                const [key, value] = cookie.trim().split('=')
                if (key === name) {
                    return decodeURIComponent(value)
                }
            }
        }
    }
    const csrftoken = getCookie('csrftoken')

    const changeLike = async (id) => {
        const like_button = document.querySelector("#" + id)
        const url = like_button.dataset.url;
        const response = await fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken,
            }
        });
        const tweet_data = await response.json();
        changeStyle(tweet_data, like_button);
    }

    const changeStyle = (tweet_data, like_button) => {
        const like_count = document.querySelector(".count_" + tweet_data.tweet_id)
        if (tweet_data.is_liked) {
            unlike_url = tweet_data.unlike_url;
            like_button.setAttribute("data-url", unlike_url);
            like_button.innerHTML = "いいね解除";
            like_count.textContent = tweet_data.like_count;
        } else {
            like_url = tweet_data.like_url;
            like_button.setAttribute("data-url", like_url);
            like_button.innerHTML = "いいね";
            like_count.textContent = tweet_data.like_count;
        }
    }
</script>